name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: install pnpm
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: install playwright
        run: pnpm exec playwright install firefox --with-deps

      - name: lint
        run: pnpm /lint:/

      - name: run tests
        run: pnpm test

      - name: build
        run: pnpm build

      - name: publish
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          pnpm publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
