name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: install pnpm
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm /lint:/

      - name: run tests
        run: pnpm test

      - name: build
        run: pnpm build

      - name: publish
        run: pnpm publish --no-git-checks --access public
